const fs = require('fs');
const path = require('path');

const changelogPath = path.join(__dirname, '../src/data/changelog.json');
let changelog = JSON.parse(fs.readFileSync(changelogPath, 'utf8'));

const translations = {
  "implement automated changelog modal fetching last 50 commits": "實作自動抓取前 50 次提交紀錄的更新紀錄對話窗",
  "move modal CSS styles to App.css so ManualAssignModal renders correctly in the center": "將對話窗樣式移至全域，修復指定學生視窗無法置中的排版問題",
  "leave seats empty on student list upload to allow manual pre-assignment before auto-assignment": "匯入名單後預設清空座位，讓使用者能在自動排座前「手動指定並鎖定」特定學生",
  "missing onClearEdit prop caused edited rules to remain in edit state, and allow editing from modal rule list": "修復規則儲存後編輯狀態未清除的異常，並支援在對話窗內直接點擊列表進行編輯",
  "syntax error due to missing closing div in RuleBuilderModal": "修復對話窗的語法渲染錯誤",
  "keep RuleBuilderModal open after saving to allow continuous addition of rules without reopening": "優化體驗：儲存規則後對話窗會保持開啟，方便老師連續建立多筆規則",
  "support editing existing seating rules by clicking on them": "支援直接點擊側邊欄的條件列表來修改現有規則",
  "allow clicking any seat to manually assign and lock a student from a searchable list before auto-assignment": "實作「指定學生至座位」功能：點擊空座位即可搜尋並綁定學生",
  "dark mode text color invisible in RuleBuilderModal student selection grid": "修復深色模式下，對話窗學生網格文字顏色太暗看不見的問題",
  "adjacency constraints failing in sparse/custom grids by replacing hardcoded threshold with nearest-neighbor detection": "升級排座演算法：導入最近鄰居 (Nearest-Neighbor) 偵測，修復自定義版面中「相鄰」條件判定失效的問題",
  "only show layout toggle button in group/exam modes, removing it from standard mode as well": "優化介面：只在小組與個人考試模式顯示版面切換按鈕",
  "hide layout toggle button in custom mode": "優化介面：在自定義版面隱藏不必要的版面切換按鈕",
  "add spacing constraint to prevent adjacent seats from belonging to the same group in custom mode auto-generation": "優化自定義版面小組自動生成：加入間距限制，避免相鄰座位被分配到同一個小組",
  "support grouping in custom mode by automatically dividing students into groups of 4 based on spatial proximity using K-Means clustering": "升級自定義版面：導入 K-Means 機器學習分群演算法，能根據座位的空間距離自動將座位分配成 4 人一組",
  "add visual indicators and group badges for custom mode to easily see student groups": "為自定義版面加入視覺標示與小組號碼牌，讓分組狀態一目瞭然",
  "support double-clicking seats to rotate them in custom mode": "支援在自定義版面中「雙擊座位」來快速旋轉座位方向",
  "add missing removeRule functionality from useSeating hook": "修復刪除排座條件按鈕沒有反應的問題",
  "ensure empty seats without a group aren't included in group validation penalties": "修復排座演算法：確保沒有組別的空座位不會錯誤地被計入「必須同組」的違規扣分中",
  "render correct group badges for different modes and fix standard mode layout": "修復不同模式下的小組標籤渲染，並優化一般模式的版面顯示",
  "support custom mode grid dragging and auto-align feature": "實作自定義版面：支援自由拖曳座位，以及加入智慧對齊網格功能",
  "add floating widget for custom layout mode configuration": "為自定義版面加入懸浮設定工具列",
  "fix button layouts in sidebar": "優化側邊欄按鈕排版",
  "add dynamic layout switching between group, exam, custom and standard modes": "支援在小組、考試、自定義與一般模式之間進行動態版面切換",
  "implement full layout generation logic for group mode and standard modes": "實作小組模式與一般模式的自動排版邏輯",
  "add UI components for Sidebar, ClassroomArea and modals": "新增側邊欄、教室主要區域與設定對話窗等核心介面元件",
  "add fetch-depth 0 to GitHub Actions checkout to fetch full git history for changelog generation": "修正 GitHub Actions 部署設定，確保更新紀錄能抓取到完整的歷史資料",
  "dynamically fetch changelog to preserve initial 50 commits and append future updates": "優化更新紀錄抓取邏輯：永久保留最初的 50 筆紀錄並動態疊加未來所有的更新",
  "correct import error in changelog generator that caused manual translations to be overwritten": "修復腳本錯誤：解決更新紀錄在雲端部署時意外覆蓋翻譯紀錄的問題",
  "UI: change changelog button text to '更新紀錄'": "優化介面：將標題旁的版本號按鈕文字改為「更新紀錄」",
  "add clear seats button to allow clearing assignments without removing students": "新增「清空座位」功能：支援一鍵清除所有已排好的座位，但保留學生名單",
  "UI: set default layout to standard mode and reorder mode buttons with rename to U型小組模式": "優化介面：設定初次載入預設為「一般模式」，並將小組模式移至最後且更名為「U型小組模式」",
  "UI: add step-by-step usage guide for custom mode in sidebar": "新增教學：在自定義模式的側邊欄加入簡單 5 步驟的使用流程引導",
  "UI: change custom mode add seats to use a numeric input field for adding multiple seats at once": "優化介面：自定義模式改為「座位總數」輸入框，支援一口氣新增指定數量的座位",
  "UI: change custom mode seat input to set total seats instead of adding incrementally": "在自定義模式中，原本新增座位是一顆顆慢慢加，現在改為直接輸入「需要的座位總數」，系統就會自動幫您產生對應數量的方正網格座位，方便老師後續拖曳微調！",
  "automatically exit edit layout mode when switching between layout modes to prevent dragging seats in standard modes": "修復切換模式的錯誤：現在切換版面時會自動退出編輯狀態，避免在一般模式下座位也能被拖曳的問題",
  "UI: dramatically increase visibility of background grid during layout editing to help users align seats": "強化格線：大幅提升自定義模式編輯時的背景格線可見度，新增雙層主副格線系統",
  "UI: remove classroom border shadow and add dynamic full-screen crosshairs when dragging seats to perfectly align them": "新增十字線對齊輔助：拖曳座位時會即時顯示貫穿全教室的藍色十字定位線",
  "Fix: stop mouse down propagation on seat delete button to prevent drag interception": "修復刪除按鈕：解決編輯模式中紅色叉叉無法點擊的問題",
  "Fix: correctly isolate deleted seats between different layout modes by clearing hidden state on switch": "修復模式隔離：不同版面模式間的座位刪除不再互相干擾",
  "feat: add snapshot system to temporarily save and restore seat arrangements across all layout modes": "在側邊欄加入了全新的「暫存座位表」功能。當您好不容易排好版面，或是想嘗試其他排法但又怕回不去時，只要點擊暫存，系統就會把當下包含版面模式、座位座標、學生位置等所有資訊都備份起來，隨時可以一鍵還原！",
  "Docs: translate recent changelogs to Chinese with full details": "更新紀錄維護：將最近所有更新紀錄補上完整的中文翻譯與詳細說明",
  "Docs: translate recent changelog entries to Traditional Chinese with detailed descriptions": "更新紀錄維護：將所有更新紀錄翻譯成繁體中文並加入詳細描述",
  "overhaul light mode colors to greatly improve readability and contrast": "全面重新設計淺色主題的配色方案，大幅提升文字可讀性與對比度",
  "remove Framer Motion 'layout' prop from Seat to prevent drifting/staircasing with translate(-50%, -50%)": "修復座位位置偏移：移除 Framer Motion 的 layout 屬性，解決座位日積月累的地址位移問題",
  "resolve seat shifting on group assignment, align new seats to grid, allow one-click deletion": "修復分組時座位位置跳動問題，新座位自動對齊格線，並支援一鍵刪除",
  "ensure manual swap handles dynamically added custom seats": "修復手動交換座位功能：現在可正確處理動態新增的自定義座位",
  "make static facilities (doors/teacher) persistent across all layout modes globally": "設施座標全域共用：門、講台等設施的位置現在會在所有模式間共享保存",
  "remove mock student list initialization": "移除預設的範例學生名單，改為讓使用者自行匯入",
  "implement snap-to-grid in custom layout mode with visual grid lines": "實作自定義版面的磁吸對齊格線功能，並顯示背景輔助格線",
  "prevent custom mode layout data loss with resilient functional localStorage and auto-recovery": "防止自定義版面資料遺失：強化 localStorage 容錯機制與自動救回",
  "enhance drag and drop for group badges with visual feedback and add click-to-paint brush mode": "升級小組號碼牌拖曳功能：加入視覺回饋並新增「點擊塗色」筆刷模式",
  "Enhancement: add groups 6-8 colors, palette unassign tool, and refine algorithm for unassigned group 0": "擴充分組功能：新增第 6~8 組顏色、「無組別」清除工具，並優化第 0 組的演算法處理",
  "correctly evaluate falsy groupId 0 in Seat and Sidebar components to keep seats blank": "修復組別爭取錯誤：確保編號為 0 的無組別座位不會被錯誤呈現",
  "enable double-click seat rotation by removing preventDefault on mousedown": "修復雙擊旋轉座位功能：移除診止滑鼠事件的預設行為",
  "revert custom layout localStorage key to prevent data loss": "還原自定義版面的儲存金鑰，避免資料遺失",
  "resolve ReferenceError student is not defined in Seat component": "修復座位元件的變數參照錯誤 (ReferenceError)",
  "hide student names during edit mode, provide 30-seat grid as default custom layout, and add reset layout button": "編輯模式隱藏學生姓名、預設提供 30 座的方正座位陣列，並新增「重置版面」按鈕",
  "correct drag offset calculation to prevent drifting, remove spring lag during edit, initialize new seats without groups, and hide static group labels in custom mode": "修正拖曳偏移計算、移除編輯模式的彈簧動畫延遲、新座位預設無組別，並隱藏自定義模式的靜態組別標籤",
  "Enhance custom mode with drag-and-drop group assignment and double-click rotation": "升級自定義模式：支援拖曳分配小組號與雙擊旋轉座位方向",
  "Add Custom Group mode with seat layout editor": "新增自定義分組模式：可自由編輯座位版面配置",
  "Expand standard mode layout bounds to prevent seat overlap": "擴大一般模式的版面範圍，避免座位互相重疊",
  "Adjust seat layout bounds to resolve overlaps": "調整座位版面範圍，解決座位重疊問題",
  "Add GitHub Actions deploy workflow to bypass GitHub Pages timeout": "新增 GitHub Actions 自動部署流程，解決 GitHub Pages 部署逾時問題",
  "Force new build hash": "強制產生新的網頁版本快取",
  "Retry GitHub Pages Deployment": "重試 GitHub Pages 部署",
  "add --nojekyll to gh-pages deploy script to fix Github Actions failure": "修正部署腳本：加入 .nojekyll 檔案解決 GitHub Actions 部署失敗",
  "Fix GitHub Pages deployment with .nojekyll": "修復 GitHub Pages 部署：加入 .nojekyll 檔案",
  "Trigger rebuild": "觸發重新建置",
  "Change static label sizes from cqw to px to prevent massive scaling": "修復設施標籤過大問題：將單位從 cqw 改為 px 避免縮放失控",
  "Adjust group mode seat coordinates to prevent overlap with static items": "調整小組模式座位座標，避免與門、講台等設施重疊",
  "standard mode seats should be horizontal": "修正一般模式座位方向：應為橫向排列",
  "Fix standard mode vertical shape and revert classroom container scaling logic to V1": "修復一般模式座位形狀與教室容器縮放邏輯",
  "Enhance light theme UI and revert seat proportions": "優化淺色主題介面與還原座位比例",
  "Fix light mode button visibility and horizontal layout seat overlaps": "修復淺色模式按鈕可見度與橫向版面座位重疊問題",
  "Fix lock button visibility, Light theme contrast, and Standard mode layout": "修復鎖定按鈕可見度、淺色主題對比度與一般模式版面",
  "V2.0 Refactor: Modularization, PWA, Framer Motion, UseSeating hook": "V2.0 架構大重構：模組化設計、PWA 離線支援、Framer Motion 動畫引擎",
  "Add hidden credits as easter eggs in source files and console": "在原始碼與主控台加入隱藏版權資訊彩蛋",
  "Add watermark to the top-right and bottom-right of the web page": "在網頁右上角與右下角加入版權浮水印",
  "Add white background JPEG export option and fix PPTX layout ratio for identical seat sizes": "新增白底 JPEG 匯出選項，並修復 PPTX 匯出的座位比例問題",
  "Fix PPTX overlap by scaling proportionally and hide UI elements in JPEG export": "修復 PPTX 座位重疊問題，並在 JPEG 匯出時隱藏多餘的介面元素",
  "Add alert when student count exceeds seat capacity": "新增警告提示：當學生數超過座位數時自動提醒",
  "stop mouse down propagation on seat delete button to prevent drag interception": "修復刪除按鈕：解決編輯模式中紅色叉叉無法點擊的問題",
  "correctly isolate deleted seats between different layout modes by clearing hidden state on switch": "修復模式隔離：不同版面模式間的座位刪除不再互相干擾",
  "add snapshot system to temporarily save and restore seat arrangements across all layout modes": "新增「暫存座位表」：可隨時手動儲存目前的排版畫面並還原",
  "Docs: translate all recent commits including grid, crosshairs, delete fix, mode isolation and snapshot feature": "更新紀錄維護：將所有近期提交紀錄翻譯為繁體中文",
  "Docs: translate remaining changelogs to Chinese with full details": "更新紀錄維護：補齊所有歷史更新紀錄的中文詳細說明",
  "make snapshot system automatic on major layout and assignment changes": "升級「自動暫存紀錄」：系統會在排座、清空或切換模式前自動備份",
  "resolve conflict between single-click seat binding and double-click rotation": "修復點擊衝突：解決雙擊旋轉座位與點擊指定學生視窗的干擾問題",
  "use manual timestamp logic for double click to bypass draggable interference": "強化雙擊偵測：重寫底層雙擊邏輯，解決無法旋轉座位的問題",
  "allow deleting extra seats in standard layout mode": "一般模式升級：新增「刪除多餘座位」功能，可自由隱藏不需要的座位"
};

const detailTranslations = {
  "implement automated changelog modal fetching last 50 commits": "實作自動抓取前 50 次提交紀錄的更新紀錄對話窗，並自動將紀錄透過精美時間軸呈現，系統會在每次部署時自動抓取最新進度。",
  "leave seats empty on student list upload to allow manual pre-assignment before auto-assignment": "為了讓老師能事先把特定學生安排在特殊座位（例如講桌旁），現在匯入名單後不再立刻自動排滿，而是留空讓老師先綁定特定座位後，再執行自動排座。",
  "adjacency constraints failing in sparse/custom grids by replacing hardcoded threshold with nearest-neighbor detection": "過去的演算法使用固定像素距離來判斷是否相鄰，導致在老師自己隨意拉動座位的「自定義版面」中判斷常常失準。現在升級為 Nearest-Neighbor 動態偵測，能精準找出每個座位周遭的鄰居，讓「不能相鄰」與「必須相鄰」的條件在任何畸形版面都能完美生效！",
  "support grouping in custom mode by automatically dividing students into groups of 4 based on spatial proximity using K-Means clustering": "在自定義版面中，老師排出的形狀可能千奇百怪。為了能自動分配小組號碼，我們導入了 K-Means 機器學習分群演算法，它會分析畫面上所有座位的 X, Y 座標，聰明地將距離相近的座位聚集成 4 人一組的小組！",
  "add clear seats button to allow clearing assignments without removing students": "在側邊欄加入紅色的「清空座位」按鈕，當老師想要重新手動安排或覺得排出來的座位不滿意時，可以直接把所有排好的座位一鍵清空，且不會刪除原本已經匯入的學生名單，省去重新上傳的麻煩。",
  "新增「清空座位」功能：支援一鍵清除所有已排好的座位，但保留學生名單": "在側邊欄加入紅色的「清空座位」按鈕，當老師想要重新手動安排或覺得排出來的座位不滿意時，可以直接把所有排好的座位一鍵清空，且不會刪除原本已經匯入的學生名單，省去重新上傳的麻煩。",
  "UI: set default layout to standard mode and reorder mode buttons with rename to U型小組模式": "將網站初次開啟時的預設版面改為最常用的「一般模式」，並將右上角的版面切換按鈕依序調整為「一般模式、自定義模式、U型小組模式」，同時將小組模式更名，使其更貼近實際排版形狀。",
  "優化介面：設定初次載入預設為「一般模式」，並將小組模式移至最後且更名為「U型小組模式」": "將網站初次開啟時的預設版面改為最常用的「一般模式」，並將右上角的版面切換按鈕依序調整為「一般模式、自定義模式、U型小組模式」，同時將小組模式更名，使其更貼近實際排版形狀。",
  "UI: add step-by-step usage guide for custom mode in sidebar": "在「自定義模式」的側邊欄最上方新增了一個醒目的「簡單 5 步驟」提示區塊，明確引導使用者如何點擊編輯、新增座位、拖曳排版、使用筆刷分組，最後完成入座的完整流程。",
  "新增教學：在自定義模式的側邊欄加入簡單 5 步驟的使用流程引導": "在「自定義模式」的側邊欄最上方新增了一個醒目的「簡單 5 步驟」提示區塊，明確引導使用者如何點擊編輯、新增座位、拖曳排版、使用筆刷分組，最後完成入座的完整流程。",
  "UI: change custom mode add seats to use a numeric input field for adding multiple seats at once": "將自定義模式中原本固定的「+1」和「+5」新增座位按鈕，升級為一個可自由輸入數字的輸入框，讓老師可以直接輸入想要的座位數量（例如 30），點擊後即可一次產生對應數量的座位。",
  "優化介面：自定義模式改為「座位總數」輸入框，支援一口氣新增指定數量的座位": "將自定義模式中原本固定的「+1」和「+5」新增座位按鈕，升級為一個可自由輸入數字的輸入框，讓老師可以直接輸入想要的座位數量（例如 30），點擊後即可一次產生對應數量的座位。",
  "UI: change custom mode seat input to set total seats instead of adding incrementally": "大幅優化自定義模式的座位產生邏輯：現在改為直接輸入「座位總數」，點擊重新產生後，系統會自動將該數量的座位排列成完美的方正網格陣型，大幅減少老師手動把座位排整齊的時間！",
  "升級排版功能：自定義模式可直接輸入「座位總數」，系統會自動重新產生方正網格排列": "大幅優化自定義模式的座位產生邏輯：現在改為直接輸入「座位總數」，點擊重新產生後，系統會自動將該數量的座位排列成完美的方正網格陣型，大幅減少老師手動把座位排整齊的時間！",
  "automatically exit edit layout mode when switching between layout modes to prevent dragging seats in standard modes": "修復了一個系統邏輯錯誤：原本在自定義模式開啟「編輯」後若直接切換到其他模式，編輯狀態並未解除，導致一般模式的座位也能被意外拖曳。現在切換任何模式都會自動退出編輯狀態，確保系統穩定。",
  "修復切換模式的錯誤：現在切換版面時會自動退出編輯狀態，避免在一般模式下座位也能被拖曳的問題": "修復了一個系統邏輯錯誤：原本在自定義模式開啟「編輯」後若直接切換到其他模式，編輯狀態並未解除，導致一般模式的座位也能被意外拖曳。現在切換任何模式都會自動退出編輯狀態，確保系統穩定。",
  "UI: dramatically increase visibility of background grid during layout editing to help users align seats": "將自定義模式的編輯背景格線從原本幾乎看不見的淡色，全面升級為清晰的雙層格線系統：每 2.5% 間距的細密基準線搭配每 10% 間距的粗主格線，讓座位排版對齊變得一目了然，就像在藍圖上作業一樣精準！",
  "強化格線：大幅提升自定義模式編輯時的背景格線可見度，新增雙層主副格線系統": "將自定義模式的編輯背景格線從原本幾乎看不見的淡色，全面升級為清晰的雙層格線系統：每 2.5% 間距的細密基準線搭配每 10% 間距的粗主格線，讓座位排版對齊變得一目了然，就像在藍圖上作業一樣精準！",
  "UI: remove classroom border shadow and add dynamic full-screen crosshairs when dragging seats to perfectly align them": "移除了多餘的教室外框光暈，並新增了全新的「動態十字線」輔助對齊系統：當您拖曳任何座位時，會即時出現貫穿整個教室的水平與垂直藍色定位線，讓您一眼就能看出是否與其他座位完美對齊！",
  "新增十字線對齊輔助：拖曳座位時會即時顯示貫穿全教室的藍色十字定位線": "移除了多餘的教室外框光暈，並新增了全新的「動態十字線」輔助對齊系統：當您拖曳任何座位時，會即時出現貫穿整個教室的水平與垂直藍色定位線，讓您一眼就能看出是否與其他座位完美對齊！",
  "Fix: stop mouse down propagation on seat delete button to prevent drag interception": "解決了編輯模式中紅色叉叉按鈕無法點擊的問題。原因是滑鼠按下時，座位拖曳事件優先攔截了點擊動作，導致刪除按鈕失效。現在已阻斷事件冒泡，叉叉可以正常點擊刪除座位了。",
  "修復刪除按鈕：解決編輯模式中紅色叉叉無法點擊的問題": "解決了編輯模式中紅色叉叉按鈕無法點擊的問題。原因是滑鼠按下時，座位拖曳事件優先攔截了點擊動作，導致刪除按鈕失效。現在已阻斷事件冒泡，叉叉可以正常點擊刪除座位了。",
  "Fix: correctly isolate deleted seats between different layout modes by clearing hidden state on switch": "修復了一個嚴重的模式間汙染問題：原本不同模式共用同一份「被隱藏座位」清單，導致在自定義模式刪除座位後，切換到一般模式會發現同編號的座位也跟著消失。現在切換模式時會自動清空暫時隱藏的紀錄，自定義模式的座位刪除也改為真正從資料中移除，徹底杜絕跨模式干擾。",
  "修復模式隔離：不同版面模式間的座位刪除不再互相干擾": "修復了一個嚴重的模式間汙染問題：原本不同模式共用同一份「被隱藏座位」清單，導致在自定義模式刪除座位後，切換到一般模式會發現同編號的座位也跟著消失。現在切換模式時會自動清空暫時隱藏的紀錄，自定義模式的座位刪除也改為真正從資料中移除，徹底杜絕跨模式干擾。",
  "feat: add snapshot system to temporarily save and restore seat arrangements across all layout modes": "新增「暫存座位表」功能區塊：老師可以在任何模式下隨時點擊「暫存目前畫面」將目前的排版狀態（包含版面模式、座位位置、學生入座狀態等）完整打包儲存。之後即使重排或清空座位，都可以從暫存列表中一鍵載入，完美還原之前的排版成果。最多可保存 10 筆暫存紀錄。",
  "新增「暫存座位表」：可隨時儲存目前的排版畫面，之後再載入還原": "新增「暫存座位表」功能區塊：老師可以在任何模式下隨時點擊「暫存目前畫面」將目前的排版狀態（包含版面模式、座位位置、學生入座狀態等）完整打包儲存。之後即使重排或清空座位，都可以從暫存列表中一鍵載入，完美還原之前的排版成果。最多可保存 10 筆暫存紀錄。",
  "Docs: translate recent changelogs to Chinese with full details": "將最近新增的更新紀錄補上完整的繁體中文翻譯和詳細的功能說明，確保每一筆紀錄都有清晰的中文描述。",
  "更新紀錄維護：將最近所有更新紀錄補上完整的中文翻譯與詳細說明": "將最近新增的更新紀錄補上完整的繁體中文翻譯和詳細的功能說明，確保每一筆紀錄都有清晰的中文描述。",
  "Docs: translate recent changelog entries to Traditional Chinese with detailed descriptions": "將所有更新紀錄的標題與內容全數翻譯成繁體中文，並為每筆重要更新加入詳細的功能描述與技術細節。",
  "更新紀錄維護：將所有更新紀錄翻譯成繁體中文並加入詳細描述": "將所有更新紀錄的標題與內容全數翻譯成繁體中文，並為每筆重要更新加入詳細的功能描述與技術細節。",
  "修復腳本錯誤：解決更新紀錄在雲端部署時意外覆蓋翻譯紀錄的問題": "修復了 generate-changelog.js 腳本中的 import 路徑錯誤，原本每次 GitHub Actions 部署時都會從零重新產生 changelog.json，導致先前手動翻譯的中文紀錄被覆蓋。現在已改為先讀取現有檔案再追加新紀錄。",
  "優化介面：將標題旁的版本號按鈕文字改為「更新紀錄」": "將右上角版本號按鈕的顯示文字從「v1.0.xx」改為「更新紀錄」，讓使用者更容易理解點擊後會看到什麼。",
  "修正 GitHub Actions 部署設定，確保更新紀錄能抓取到完整的歷史資料": "在 deploy.yml 中加入 fetch-depth: 0 參數，解決 GitHub Actions 預設只拉取最新一筆提交的問題，現在能正確抓取到所有歷史提交紀錄來產生完整的更新時間軸。",
  "優化更新紀錄抓取邏輯：永久保留最初的 50 筆紀錄並動態疊加未來所有的更新": "重新設計了 changelog 的產生邏輯：先讀取現有的 changelog.json 中已有的紀錄，再從 git log 中只抓取「比最新一筆更新」的提交，這樣既保留了最早期的 50 筆歷史紀錄，也能持續疊加新的更新。",
  "將對話窗樣式移至全域，修復指定學生視窗無法置中的排版問題": "將「指定學生至座位」對話窗的 CSS 樣式從元件內部移至 App.css 全域樣式表，解決了對話窗無法居中顯示的問題。",
  "修復規則儲存後編輯狀態未清除的異常，並支援在對話窗內直接點擊列表進行編輯": "修復了儲存排座規則後，上一次編輯的狀態沒有被清空的問題，同時新增了直接在對話窗內點擊現有規則即可進入編輯模式的功能。",
  "修復對話窗的語法渲染錯誤": "修復了排座規則對話窗中的 JSX 語法錯誤，解決網頁在開啟設定時白屏的問題。",
  "優化體驗：儲存規則後對話窗會保持開啟，方便老師連續建立多筆規則": "改善了設定排座條件的操作流程：原本儲存一筆規則後對話窗會關閉，如果要建立多筆規則就得一直重開。現在儲存後對話窗會繼續保持開啟並清空表單，方便老師一口氣建立所有條件。",
  "支援直接點擊側邊欄的條件列表來修改現有規則": "讓老師可以直接點擊側邊欄已存在的排座條件（例如「小明不能坐小華旁邊」），即可直接跳出編輯視窗修改該條規則，不用再刪除後重建。",
  "實作「指定學生至座位」功能：點擊空座位即可搜尋並綁定學生": "新增了強大的「手動指定學生」功能：點擊任何一個空座位，會彈出一個可搜尋的學生名單，選擇學生後即可將其綁定並鎖定在該座位，自動排座時不會被移動。",
  "修復深色模式下，對話窗學生網格文字顏色太暗看不見的問題": "修復了在深色主題下，「指定學生至座位」對話窗中的學生名字顏色太深導致在深色背景上幾乎看不見的問題。",
  "優化介面：只在小組與個人考試模式顯示版面切換按鈕": "在一般模式與自定義模式下隱藏「切換為橫排/直排」按鈕，避免使用者誤觸不相關的功能。",
  "全面重新設計淺色主題的配色方案，大幅提升文字可讀性與對比度": "針對淺色主題進行了全面的色彩重新設計，運用 Zinc 色系作為基底配色，大幅提升按鈕、文字、輸入框與座位卡片的對比度，讓淺色模式下的閱讀體驗大幅提升。",
  "修復座位位置偏移：移除 Framer Motion 的 layout 屬性，解決座位日積月累的地址位移問題": "移除了 Framer Motion 的 layout 屬性，該屬性會與座位的 translate(-50%, -50%) CSS 置中過渡產生衝突，導致座位每次重新渲染時都會微微偏移，經過多次操作後座位會呈現階梯狀的漂移。",
  "修復分組時座位位置跳動問題，新座位自動對齊格線，並支援一鍵刪除": "修復了在自定義模式中點擊分配小組後，座位會突然跳到奇怪位置的問題。同時新增座位時會自動對齊到最近的格線上，並支援點擊紅色叉叉一鍵刪除座位。",
  "修復手動交換座位功能：現在可正確處理動態新增的自定義座位": "修復了當自定義模式動態新增座位後，拖曳交換學生座位會失效的問題。原因是 assignments 陣列中沒有包含新增座位的索引。",
  "設施座標全域共用：門、講台等設施的位置現在會在所有模式間共享保存": "將門、講台等靜態設施的座標統一儲存在同一個 localStorage key 中，這樣在一般模式下拖動了門的位置後，切換到自定義模式也會看到相同的位置。",
  "移除預設的範例學生名單，改為讓使用者自行匯入": "移除了原本預設內建的範例學生名單（王小明、李小華…），現在網站初始狀態會顯示空白名單，引導使用者自行上傳檔案。",
  "實作自定義版面的磁吸對齊格線功能，並顯示背景輔助格線": "在自定義版面的編輯模式中，座位現在會自動吸附到最近的 2.5% 格線交叉點上，同時教室背景會顯示淡色的輔助格線，讓座位對齊變得輕而易舉。",
  "防止自定義版面資料遺失：強化 localStorage 容錯機制與自動救回": "強化了自定義版面的 localStorage 讀寫機制，增加了資料損壞時的自動救回邏輯，避免老師辛苦排好的自定義座位配置因儲存異常而消失。",
  "升級小組號碼牌拖曳功能：加入視覺回饋並新增「點擊塗色」筆刷模式": "升級了自定義模式中小組號碼牌的拖曳體驗，現在拖曳時會有明確的視覺回饋（發光效果），並新增了「點擊塗色」筆刷模式：點選一個號碼後，可以連續點擊多個座位快速上色。",
  "擴充分組功能：新增第 6~8 組顏色、「無組別」清除工具，並優化第 0 組的演算法處理": "將分組數從原本的 5 組擴充到 8 組，每組都有獨特的顏色。同時新增了「無」清除工具，可以將已分配的座位改回無組別狀態，並優化了演算法對於編號 0（無組別）座位的處理邏輯。",
  "修復組別爯取錯誤：確保編號為 0 的無組別座位不會被錯誤呈現": "修復了 JavaScript 中 groupId === 0 被誤判為 falsy 的問題，導致「無組別」的座位被錯誤顯示為有組別狀態。",
  "修復雙擊旋轉座位功能：移除診止滑鼠事件的預設行為": "移除了 mousedown 事件中的 preventDefault，解決了座位無法通過雙擊來旋轉方向的問題。",
  "還原自定義版面的儲存金鑰，避免資料遺失": "將自定義版面的 localStorage key 還原為原本的名稱，避免因金鑰變更導致老師先前的自定義座位配置被視為不存在。",
  "修復座位元件的變數參照錯誤 (ReferenceError)": "修復了 Seat.jsx 元件中引用了未定義的 student 變數的問題，該錯誤會導致整個教室區域白屏。",
  "編輯模式隱藏學生姓名、預設提供 30 座的方正座位陣列，並新增「重置版面」按鈕": "編輯模式下會隱藏學生姓名以避免干擾排版，預設的自定義版面提供 30 個座位的方正陣列作為起始點，並新增「重置版面」按鈕讓老師可以快速回到初始狀態。",
  "修正拖曳偏移計算、移除編輯模式的彈簧動畫延遲、新座位預設無組別，並隱藏自定義模式的靜態組別標籤": "一次修復了四個自定義模式的問題：(1) 拖曳時座位會偏離滑鼠位置；(2) 編輯模式下座位移動有彈簧動畫延遲；(3) 新增的座位被預設分配到第 1 組；(4) 自定義模式下顯示了不相關的靜態組別標籤。",
  "升級自定義模式：支援拖曳分配小組號與雙擊旋轉座位方向": "在自定義模式中加入了兩個重要功能：可以將小組號碼牌直接拖曳到座位上來分配組別，以及雙擊座位即可旋轉其方向（橫向/直向）。",
  "新增自定義分組模式：可自由編輯座位版面配置": "全新的「自定義分組模式」讓老師可以完全自由地設計教室的座位配置，包括新增、刪除、拖曳移動座位，以及自行定義每個座位所屬的小組。",
  "擴大一般模式的版面範圍，避免座位互相重疊": "擴大了一般模式中座位的可用範圍，解決當行列數較多時座位會互相重疊的問題。",
  "調整座位版面範圍，解決座位重疊問題": "微調座位的 X/Y 座標計算公式，解決在特定行列組合下座位會重疊的問題。",
  "新增 GitHub Actions 自動部署流程，解決 GitHub Pages 部署逾時問題": "建立了完整的 GitHub Actions CI/CD 工作流程，取代原本的手動部署，解決了 GitHub Pages 經常部署逾時失敗的問題。",
  "強制產生新的網頁版本快取": "強制觸發一次新的建置，确保網頁的網址不會因瀏覽器快取而显示舊版內容。",
  "重試 GitHub Pages 部署": "重新觸發 GitHub Pages 部署流程。",
  "修正部署腳本：加入 .nojekyll 檔案解決 GitHub Actions 部署失敗": "在 gh-pages 部署腳本中加入 --nojekyll 參數，解決 GitHub Pages 將專案的底線開頭檔案視為 Jekyll 特殊檔案而忽略的問題。",
  "修復 GitHub Pages 部署：加入 .nojekyll 檔案": "在專案根目錄加入 .nojekyll 空檔案，告訴 GitHub Pages 不要使用 Jekyll 渲染，解決部署失敗的問題。",
  "觸發重新建置": "觸發一次新的建置以測試部署流程。",
  "修復設施標籤過大問題：將單位從 cqw 改為 px 避免縮放失控": "將門、講台等設施標籤的字體大小從 cqw（容器查詢寬度）改為固定的 px 單位，解決了在某些螢幕尺寸下標籤文字會變得巨大的問題。",
  "調整小組模式座位座標，避免與門、講台等設施重疊": "微調了小組模式的座位座標，避免座位與教室的門、講台等靜態設施發生位置重疊。",
  "修正一般模式座位方向：應為橫向排列": "修正了一般模式下座位的方向，從錯誤的直向改為橫向，以符合實際教室的座位擺放方式。",
  "修復一般模式座位形狀與教室容器縮放邏輯": "修復了一般模式的座位形狀顯示異常，並將教室容器的縮放邏輯還原為 V1 版本的穩定方案。",
  "優化淺色主題介面與還原座位比例": "針對淺色主題調整了按鈕、卡片、背景等的顏色對比度，並將座位的寬高比例還原為更合理的數值。",
  "修復淺色模式按鈕可見度與橫向版面座位重疊問題": "修復了淺色主題下按鈕文字顏色太淡導致看不見的問題，並解決了橫向版面中座位互相重疊的問題。",
  "修復鎖定按鈕可見度、淺色主題對比度與一般模式版面": "一次修復了三個介面問題：座位的鎖定按鈕在某些情況下看不見、淺色主題的整體對比度不足、以及一般模式的座位版面異常。",
  "V2.0 架構大重構：模組化設計、PWA 離線支援、Framer Motion 動畫引擎": "將整個專案從單一檔案全面重構為模組化架構：將狀態管理抽離為 useSeating hook、將介面拆分為 Header/Sidebar/ClassroomArea/Seat 等獨立元件、加入 PWA 支援以實現離線使用、以及導入 Framer Motion 實現座位切換的流暢動畫效果。",
  "在原始碼與主控台加入隱藏版權資訊彩蛋": "在網頁的原始碼註解與瀏覽器主控台中加入了隱藏的開發者版權資訊與彩蛋。",
  "在網頁右上角與右下角加入版權浮水印": "在網頁介面的右上角和右下角加入了半透明的版權浮水印文字。",
  "新增白底 JPEG 匯出選項，並修復 PPTX 匯出的座位比例問題": "新增了「白底圖檔」匯出選項，讓老師可以選擇匯出黑底或白底的 JPEG 圖片。同時修復了 PPTX 匯出時座位大小不一致的問題。",
  "修復 PPTX 座位重疊問題，並在 JPEG 匯出時隱藏多餘的介面元素": "修復了 PPTX 匯出時座位互相重疊的問題（改用等比例縮放），並在 JPEG 匯出時自動隱藏按鈕、提示文字等介面元素，確保匯出的圖片乾淨專業。",
  "新增警告提示：當學生數超過座位數時自動提醒": "當使用者上傳的學生數量超過目前版面的座位數量時，系統會彈出明確的警告視窗告知，避免老師以為系統當機。"
};

changelog.forEach(entry => {
  const originalTitle = entry.title;
  if (translations[originalTitle]) {
    entry.title = translations[originalTitle];
  }
  
  if (detailTranslations[originalTitle]) {
    entry.details = detailTranslations[originalTitle];
  } else if (!entry.details) {
    entry.details = "優化了系統內部穩定性與細節操作體驗。";
  }
});

fs.writeFileSync(changelogPath, JSON.stringify(changelog, null, 2), 'utf8');
console.log('Changelog translated!');
